import dynamic from "next/dynamic"
import Head from "next/head"

import { Experiment } from "../components/Experiment"
import { InstantBandit } from "../components/InstantBandit"
import { InstantBanditProps } from "../lib/types"
import { DEMO_SITE } from "../lib/examples"

import styles from "../styles/Home.module.css"
import NoSSR from "../components/NoSSR"
import { Debug } from "../components/InstantBanditDebug"
import { useContext } from "react"
import { ScopeContext } from "../lib/contexts"



export default function ClientSideRendering() {
  return (
    <NoSSR>
      <div className={styles.container}>
        <Head>
          <title>Instant Bandit :: CSR</title>
          <meta name="description" content="Generated by create next app" />
          <link
            rel="icon"
            // See https://css-tricks.com/emojis-as-favicons/
            href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>⚔️</text></svg>"
          />
        </Head>

        <InstantBandit>
          <main className={styles.main}>
            <h1 className={styles.description}>NextJS CSR test</h1>
            <>
              <div style={{ minHeight: "2em" }}>
                <Experiment name="A">
                  <h1 style={{ background: "red" }}>Welcome! You are currently viewing experiment A</h1>
                </Experiment>
                <Experiment name="B">
                  <h1 style={{ background: "green" }}>Welcome! You are currently viewing experiment B</h1>
                </Experiment>
                <Experiment name="C">
                  <h1 style={{ background: "blue" }}>Welcome! You are currently viewing experiment C</h1>
                </Experiment>
              </div>
            </>
          </main>
        </InstantBandit>

        <footer className={styles.footer}>
          <a href="/api/_hello" target="_blank">
            Is the server running?
          </a>
          <a href="/api/_database" target="_blank">
            Is the database running?
          </a>
        </footer>
      </div>
    </NoSSR>
  )
}
