import Head from "next/head"

import { Variant } from "../components/Variant"
import { InstantBandit } from "../components/InstantBandit"
import { Placeholder } from "../components/Placeholder"
import NoSSR from "../components/NoSSR"

import styles from "../styles/Home.module.css"


export default function ClientSideRendering() {
  return (
    <NoSSR>
      <div className={styles.container}>
        <Head>
          <title>Instant Bandit :: CSR</title>
          <meta name="description" content="Generated by create next app" />
          <link
            rel="icon"
            // See https://css-tricks.com/emojis-as-favicons/
            href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>⚔️</text></svg>"
          />
        </Head>

        <InstantBandit>
          <main className={styles.main}>
            <h1 className={styles.header}>NextJS CSR/SSG test</h1>
            <p className={styles.description}>
              This example explicitly disables server-side rendering.
              Loading and variant selection is done entirely in the browser.
              This use case is where we expect to see the most CLS due to network latency.
            </p>
            <>
              <div className={styles.example}>
                <Placeholder>
                  <h1 style={{ opacity: 0 }}>Invisible placeholder element to preserve layout</h1>
                </Placeholder>

                <Variant name="A">
                  <h1 style={{ background: "red" }}>Welcome! You are currently viewing variant A</h1>
                </Variant>
                <Variant name="B">
                  <h1 style={{ background: "green" }}>Welcome! You are currently viewing variant B</h1>
                </Variant>
                <Variant name="C">
                  <h1 style={{ background: "blue" }}>Welcome! You are currently viewing variant C</h1>
                </Variant>
              </div>
            </>
          </main>
        </InstantBandit>

        <footer className={styles.footer}>
          <a href="/api/_hello" target="_blank">
            Is the server running?
          </a>
          <a href="/api/_database" target="_blank">
            Is the database running?
          </a>
        </footer>
      </div>
    </NoSSR>
  )
}
