import { GetServerSideProps } from "next"
import Head from "next/head"

import { DemoComponent, demoExperimentId } from "../components/DemoComponent"
import { Variant } from "../components/Variant"
import { InstantBandit } from "../components/InstantBandit"
import { DEMO_SITE } from "../lib/examples"
import { InstantBanditClient } from "../lib/InstantBandit"
import { sendConversion } from "../lib/lib"
import { InstantBanditProps } from "../lib/types"

import styles from "../styles/Home.module.css"



export default function Home(serverSideProps: InstantBanditProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Instant Bandit</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          // See https://css-tricks.com/emojis-as-favicons/
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>⚔️</text></svg>"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.header}>Welcome to Instant Bandit</h1>

        <div className={styles.example}>
          <InstantBandit {...serverSideProps}>
            <Variant default>
              <h1 style={{ opacity: 0.0 }}>
                This is a placeholder content.
                Normally it would not have content it.
                Placeholders are intended to fill space, preserving layout and preventing CLS.
              </h1>
            </Variant>
            <Variant name="A">
              <h1 style={{ background: "red" }}>Welcome! You are currently viewing variant A</h1>
            </Variant>
            <Variant name="B">
              <h1 style={{ background: "green" }}>Welcome! You are currently viewing variant B</h1>
            </Variant>
            <Variant name="C">
              <h1 style={{ background: "blue" }}>Welcome! You are currently viewing variant C</h1>
            </Variant>
          </InstantBandit>
        </div>

      </main>

      <footer className={styles.footer}>
        <a href="/api/_hello" target="_blank">
          Is the server running?
        </a>
        <a href="/api/_database" target="_blank">
          Is the database running?
        </a>
      </footer>
    </div >
  )
}

// Comment out to have loading done in the browser
const client = new InstantBanditClient()
export const getServerSideProps: GetServerSideProps<InstantBanditProps> = async () => {
  const site = await client.load()
  return {
    props: {
      site,
    }
  }
}
