import { GetServerSideProps } from "next"
import Head from "next/head"

import { InstantBandit } from "../components/InstantBanditComponent"
import { InstantBanditClient } from "../lib/InstantBandit"
import { InstantBanditProps } from "../lib/types"
import { Mark } from "../components/Mark"
import { Placeholder } from "../components/Placeholder"
import { Variant } from "../components/Variant"
import { sendConversion } from "../lib/lib"

import styles from "../styles/Home.module.css"
import NoSSR from "../components/NoSSR"



export default function Home(serverSideProps: InstantBanditProps) {
  return (
    <NoSSR>
      <div className={styles.container}>
        <Head>
          <title>Instant Bandit</title>
          <meta name="description" content="Generated by create next app" />
          <link
            rel="icon"
            // See https://css-tricks.com/emojis-as-favicons/
            href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>⚔️</text></svg>"
          />
        </Head>
        <Mark id="IB1">
          <InstantBandit {...serverSideProps}>
            <main className={styles.main}>
              <h1 className={styles.header}>Welcome to Instant Bandit</h1>
              <p>
                This page is rendered on-the-fly on the server (SSR) and "hydrated" on the client.
              </p>

              <div className={styles.example}>
                <Placeholder>
                  <h1 style={{ opacity: 0 }}>Invisible placeholder element to preserve layout</h1>
                </Placeholder>

                <Variant name="A">
                  <h1 style={{ background: "red" }}>Welcome! You are currently viewing variant A</h1>
                </Variant>
                <Variant name="B">
                  <h1 style={{ background: "green" }}>Welcome! You are currently viewing variant B</h1>
                </Variant>
                <Variant name="C">
                  <h1 style={{ background: "blue" }}>Welcome! You are currently viewing variant C</h1>
                </Variant>
              </div>

            </main>
          </InstantBandit>
        </Mark>
        <footer className={styles.footer}>
          <a href="/api/_hello" target="_blank">
            Is the server running?
          </a>
          <a href="/api/_database" target="_blank">
            Is the database running?
          </a>
        </footer>
      </div >
    </NoSSR>
  )
}

// Comment out to have loading done in the browser
const bandit = new InstantBanditClient()
export const getServerSideProps: GetServerSideProps<InstantBanditProps> = async () => {
  const site = await bandit.load()
  return {
    props: {
      site,
    }
  }
}
