import { GetServerSideProps } from "next"
import Head from "next/head"

import { Experiment } from "../components/Experiment"
import { InstantBandit } from "../components/InstantBandit"
import { InstantBanditClient } from "../lib/InstantBandit"
import { InstantBanditProps } from "../lib/types"
import { DEMO_SITE } from "../lib/examples"

import styles from "../styles/Home.module.css"



export default function Static(serverSideProps: InstantBanditProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Instant Bandit :: SSR</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          // See https://css-tricks.com/emojis-as-favicons/
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>⚔️</text></svg>"
        />
      </Head>

      <InstantBandit {...serverSideProps}>
        <main className={styles.main}>
          <h1 className={styles.description}>NextJS SSR test</h1>
          <>
            <div style={{ minHeight: "2em", background: "pink" }}>
              <Experiment name="A">
                <h1 style={{ background: "red" }}>Welcome! You are currently viewing experiment A</h1>
              </Experiment>
              <Experiment name="B">
                <h1 style={{ background: "green" }}>Welcome! You are currently viewing experiment B</h1>
              </Experiment>
              <Experiment name="C">
                <h1 style={{ background: "blue" }}>Welcome! You are currently viewing experiment C</h1>
              </Experiment>
            </div>
          </>
        </main>
      </InstantBandit>

      <footer className={styles.footer}>
        <a href="/api/_hello" target="_blank">
          Is the server running?
        </a>
        <a href="/api/_database" target="_blank">
          Is the database running?
        </a>
      </footer>
    </div >

  )
}

// TODO: Need to use client to perform selection as well
const client = new InstantBanditClient()
export const getStaticProps: GetServerSideProps<InstantBanditProps> = async () => {
  return {
    props: {
      site: await client.load("localhost", "123"),
    }
  }
}
